from enum import StrEnum

class FixityBasis(StrEnum):
    DRIVE_NATIVE_SHA256 = "DRIVE_NATIVE_SHA256"
    LOCAL_SHA256 = "LOCAL_SHA256"
    GOOGLE_NATIVE_REVISION_EXPORT = "GOOGLE_NATIVE_REVISION_EXPORT"
    NO_CHECKSUM_RETURNED = "NO_CHECKSUM_RETURNED"

class TxAction(StrEnum):
    RENAME = "RENAME"
    MOVE = "MOVE"
    RENAME_MOVE = "RENAME_MOVE"
    COPY = "COPY"

class TxState(StrEnum):
    DRAFT = "DRAFT"
    HITL_PENDING = "HITL_PENDING"
    APPROVED = "APPROVED"
    PRECONDITION_CHECK = "PRECONDITION_CHECK"
    EXECUTING = "EXECUTING"
    APPLIED = "APPLIED"
    READBACK_VERIFIED = "READBACK_VERIFIED"
    CLOSED = "CLOSED"
    STALE = "STALE"
    CONFLICT = "CONFLICT"
    FAILED = "FAILED"
    ROLLBACK_PENDING = "ROLLBACK_PENDING"
    ROLLED_BACK = "ROLLED_BACK"
    CANCELLED = "CANCELLED"
